<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>1701;1702;IDE0063;IDE0290</NoWarn>
    <AssemblyTitle>neXn SteamController 2026 SDL3</AssemblyTitle>
    <AssemblyName>neXn.SteamController2026.SDL3</AssemblyName>
    <RootNamespace>neXn.SteamController2026.SDL3</RootNamespace>
    <Version>1.0.1</Version>

    <!-- NuGet identity -->
    <PackageId>neXn.SteamController2026.SDL3</PackageId>
    <PackageVersion>1.0.1</PackageVersion>
    <Title>SteamController2026.SDL3</Title>
    <Authors>Dante Karl Wackermann</Authors>

    <!-- Description -->
    <Description>
      A lightweight .NET library for reading battery state and charge percentage from the 2026 Steam Controller using SDL3.
    </Description>
    <PackageDescription>
      A lightweight .NET library for detecting the 2026 Steam Controller and
      reading its battery percentage and power state through SDL3.

      Supports USB, Bluetooth, Proteus wireless puck, and Nereid wireless puck connections.
    </PackageDescription>

    <!-- Discoverability -->
    <PackageTags>
      steam-controller;steam-controller-2026;steamcontroller;valve;sdl3;gamepad;controller;battery;dotnet;csharp
    </PackageTags>

    <!-- URLs -->
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/spreedated/SteamController2026.SDL3</PackageProjectUrl>
    <RepositoryUrl>https://github.com/spreedated/SteamController2026.SDL3.git</RepositoryUrl>

    <!-- License -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

    <!-- NuGet presentation -->
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <!-- Copyright -->
    <Copyright>2026 © Dante Karl Wackermann</Copyright>

    <!-- Packing -->
    <IsPackable>true</IsPackable>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <PackageOutputPath>$(OutputPath)</PackageOutputPath>

    <!-- Symbols / debugging -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>

    <!-- Reproducible builds / repository information -->
    <Deterministic>true</Deterministic>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
    <None Include="../assets/icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="SDL3-CS" Version="3.4.16" />
  </ItemGroup>
  
  

</Project>
